#define_import_path types

// Auto-generated by wgsl_autogen — do not edit

struct GpuCamera {
    position: vec3<f32>,
    lookat: vec3<f32>,
}

struct GpuMeta {
    width: u32,
    height: u32,
    camera: GpuCamera,
}

struct GpuTextureSolidColorData {
    albedo: vec3<f32>,
}

const GPUTEXTURE_SOLIDCOLOR: u32 = 0u;

struct GpuTexture {
    material_type: u32,
    data: array<vec4<f32>, 1>,
}

struct GpuMaterialLambertianData {
    texture: GpuTexture,
}

const GPUMATERIAL_LAMBERTIAN: u32 = 0u;

struct GpuMaterial {
    material_type: u32,
    data: array<vec4<f32>, 2>,
}

fn unpack_GpuMeta(data: array<vec4<f32>, 3>) -> GpuMeta {
    return GpuMeta(bitcast<u32>(data[0].x), bitcast<u32>(data[0].y), GpuCamera(data[1].xyz, data[2].xyz));
}

fn unpack_GpuCamera(data: array<vec4<f32>, 2>) -> GpuCamera {
    return GpuCamera(data[0].xyz, data[1].xyz);
}

fn unpack_GpuMaterial_Lambertian(v: GpuMaterial) -> GpuMaterialLambertianData {
    return GpuMaterialLambertianData(GpuTexture(bitcast<u32>(v.data[0].x), array<vec4<f32>, 1>(v.data[1])));
}

fn unpack_GpuTexture_SolidColor(v: GpuTexture) -> GpuTextureSolidColorData {
    return GpuTextureSolidColorData(v.data[0].xyz);
}
