// Auto-generated by wgsl_autogen — do not edit

struct Color {
    base: vec3<f32>,
}

struct GpuTextureSolidColorData {
    albedo: Color,
}

const GPUTEXTURE_SOLIDCOLOR: u32 = 0u;

struct GpuTexture {
    material_type: u32,
    data: array<vec4<f32>, 1>,
}

struct GpuMaterialLambertianData {
    texture: GpuTexture,
}

const GPUMATERIAL_LAMBERTIAN: u32 = 0u;

struct GpuMaterial {
    material_type: u32,
    data: array<vec4<f32>, 2>,
}
